import { StyleSheet } from "react-native";
import React, { useMemo } from "react";
import { COLORS, colors } from "../../constants/colors";

export const styles = StyleSheet.create({
  screenRoot: {
    flex: 1,
  },
  Container: {
    backgroundColor: COLORS.secondaryFontColor,
    borderTopLeftRadius: 30,
  },
  contentOnTop: {
    zIndex: 1,
    backgroundColor: COLORS.secondaryFontColor,
    borderTopLeftRadius: 30,
  },
  graphSection: {
    padding: 16,
    paddingBottom: 5,
  },
  energySummaryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  energyText: {
    color: COLORS.primaryFontColor,
    fontSize: 14,
    fontFamily: "Manrope-Bold",
  },
  toggleGroup: {
    flexDirection: "row",
    alignItems: "center",
  },
  toggleGroupColumn: {
    flexDirection: "column",
    alignItems: "flex-end",
    minWidth: 130,
  },
  dailyText: {
    color: COLORS.primaryFontColor,
    fontSize: 12,
    fontFamily: "Manrope-Medium",
    paddingHorizontal: 8,
    paddingVertical: 4,
    minWidth: 50,
    textAlign: "center",
  },
  monthlyText: {
    color: COLORS.secondaryColor,
    fontSize: 12,
    fontFamily: "Manrope-Medium",
    paddingHorizontal: 8,
    paddingVertical: 4,
    minWidth: 50,
    textAlign: "center",
  },
  LastCommunicationText: {
    color: COLORS.secondaryFontColor,
    fontSize: 10,
    fontFamily: "Manrope-SemiBold",
  },
  separator: {
    color: COLORS.primaryFontColor,
    fontSize: 12,
    fontFamily: "Manrope-Regular",
    marginHorizontal: 4,
    paddingVertical: 4,
  },
  pickDateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#FAFAFA",
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 5,
  },
  pickDateText: {
    fontSize: 12,
    fontFamily: "Manrope-Medium",
    color: COLORS.primaryColor,
  },
  pickDateIcon: {
    flexShrink: 0,
  },
  textToggleContainer: {
    flexDirection: "row",
    alignItems: "center",
    minWidth: 120,
    justifyContent: "flex-end",
  },
  toggleText: {
    fontSize: 12,
    fontFamily: "Manrope-Medium",
  },
  toggleTextItem: {
    color: COLORS.primaryFontColor,
    fontSize: 12,
    fontFamily: "Manrope-Medium",
  },
  toggleTextSelected: {
    color: COLORS.secondaryColor,
  },
  toggleSeparator: {
    color: COLORS.primaryFontColor,
    fontSize: 12,
    fontFamily: "Manrope-Regular",
    marginHorizontal: 4,
  },
  toggleButton: {
    minHeight: 30,
    paddingHorizontal: 8,
  },
  graphsContainer: {
    backgroundColor: "#eef8f0",
    paddingHorizontal: 15,
    paddingTop: 15,
    borderRadius: 5,
    paddingBottom: 5,
    overflow: "hidden",
  },
  usageSummaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  usageSummaryLeft: {
    flex: 1,
  },
  usageValueRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 6,
    gap: 8,
  },
  percentRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  viewDropdownWrapper: {
    marginLeft: 12,
  },
  viewDropdownButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.secondaryColor,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 5,
    gap: 6,
    minHeight: 36,
  },
  viewDropdownButtonText: {
    color: COLORS.secondaryFontColor,
    fontSize: 13,
    fontFamily: "Manrope-SemiBold",
  },
  viewDropdownOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.2)",
  },
  viewDropdownContent: {
    backgroundColor: COLORS.secondaryFontColor,
    borderRadius: 5,
    minWidth: 140,
  },
  viewDropdownItem: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomLeftRadius: 5,
    borderBottomRightRadius: 5,
  },
  viewDropdownItemSelected: {
    backgroundColor: "#E8F5E9",
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
  },
  viewDropdownItemText: {
    fontSize: 14,
    fontFamily: "Manrope-Medium",
    color: COLORS.primaryFontColor,
  },
  viewDropdownItemTextSelected: {
    color: COLORS.secondaryColor,
    fontFamily: "Manrope-SemiBold",
  },
  timePeriodRow: {
    flexDirection: "row",
    marginTop: 16,
    gap: 8,
  },
  timePeriodButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  timePeriodButtonActive: {
    backgroundColor: colors.color_brand_blue,
  },
  timePeriodButtonText: {
    fontSize: 13,
    fontFamily: "Manrope-SemiBold",
    color: COLORS.primaryFontColor,
  },
  timePeriodButtonTextActive: {
    color: COLORS.secondaryFontColor,
  },
  thismonthText: {
    color: COLORS.primaryFontColor,
    fontSize: 14,
    fontFamily: "Manrope-Regular",
  },
  kwhText: {
    color: COLORS.secondaryColor,
    fontSize: 14,
    fontFamily: "Manrope-Bold",
  },
  tenPercentageTextContainer: {
    backgroundColor: COLORS.secondaryColor,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 8,
    borderRadius: 20,
    height: 19,
    gap: 4,
  },
  percentText: {
    color: COLORS.secondaryFontColor,
    fontSize: 12,
    fontFamily: "Manrope-SemiBold",
    lineHeight: 16,
    includeFontPadding: false,
  },
  lastText: {
    color: COLORS.primaryFontColor,
    fontSize: 12,
    fontFamily: "Manrope-Regular",
  },
  logo: {
    width: 70,
    height: 70,
    zIndex: 1,
  },
  ripple: {
    position: "absolute",
    borderWidth: 1.2,
    borderColor: "#ffffff50",
  },
  amountSection: {
    paddingHorizontal: 16,
    backgroundColor: "#eef8f0",
  },
  amountContainer: {
    backgroundColor: COLORS.primaryColor,
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 10,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderRadius: 5,
    alignItems: "center",
    paddingHorizontal: 16,
    marginTop: 10,
  },
  paynowboxContainer: {
    flexDirection: "column",
    alignItems: "flex-end",
    gap: 12,
  },
  dueText: {
    color: COLORS.secondaryFontColor,
    fontSize: 14,
    fontFamily: "Manrope-Medium",
  },
  dueDaysText: {
    color: COLORS.secondaryFontColor,
    fontSize: 12,
    fontFamily: "Manrope-Medium",
  },
  dateText: {
    color: COLORS.secondaryFontColor,
    fontSize: 11,
    fontFamily: "Manrope-Regular",
  },
  greenBox: {
    flexDirection: "row",
    backgroundColor: COLORS.secondaryColor,
    borderRadius: 5,
    justifyContent: "space-between",
    paddingHorizontal: 12,
    alignItems: "center",
    padding: 10,
    marginVertical: 4,
  },
  payInfoContainer: {
    flexDirection: "row",
  },
  shieldIcon: {
    marginRight: 12,
    marginTop: 10,
  },
  payText: {
    color: COLORS.secondaryFontColor,
    fontSize: 16,
    fontFamily: "Manrope-Bold",
  },
  tostayText: {
    color: COLORS.secondaryFontColor,
    fontSize: 16,
    fontFamily: "Manrope-Bold",
  },
  avoidText: {
    color: COLORS.secondaryFontColor,
    fontSize: 12,
    fontFamily: "Manrope-Medium",
  },
  paynowbox: {
    backgroundColor: COLORS.secondaryFontColor,
    height: 35,
    width: 95,
    borderRadius: 5,
    justifyContent: "center",
  },
  paynowText: {
    color: COLORS.primaryFontColor,
    fontSize: 12,
    fontFamily: "Manrope-Medium",
    textAlign: "center",
  },
  meterContainer: {
    paddingHorizontal: 16,
    paddingBottom: 20,
    backgroundColor: "#eef8f0",
  },
  meterInfoContainer: {
    backgroundColor: COLORS.primaryColor,
    borderRadius: 5,
    paddingTop: 13,
    paddingBottom: 13,
    paddingLeft: 13,
    paddingRight: 13,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "stretch",
    minHeight: 90,
  },
  leftContainer: {
    flexDirection: "column",
    justifyContent: "space-between",
    flex: 1,
    marginRight: 10,
  },
  meterInfoRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    gap: 10,
  },
  meterConsumerRow: {
    flexDirection: "column",
    justifyContent: "flex-start",
    gap: 13,
  },
  lastCommunicationLabelWrap: {
    marginLeft: 40,
  },
  LastCommunicationRow: {
    flexDirection: "column",
    justifyContent: "flex-end",
    alignItems: "flex-end",
  },
  meterConsumerText: {
    color: COLORS.secondaryFontColor,
    width: "70%",
    fontSize: 14,
    fontFamily: "Manrope-Bold",
  },
  meterNumberText: {
    color: COLORS.secondaryFontColor,
    fontSize: 12,
    fontFamily: "Manrope-Bold",
  },
  rightContainer: {
    flexDirection: "column",
    alignItems: "flex-end",
    justifyContent: "space-between",
    flex: 1,
    gap: 4,
  },
  rightBlockEnd: {
    alignSelf: "flex-end",
  },
  tapIndicator: {
    backgroundColor: COLORS.secondaryColor,
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 10,
  },
  tapIndicatorText: {
    fontSize: 10,
    fontFamily: "Manrope-SemiBold",
    color: COLORS.secondaryFontColor,
  },
  meterUIDText: {
    color: COLORS.primaryFontColor,
    fontSize: 10,
    fontFamily: "Manrope-Medium",
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  lastCommunicationContainer: {
    backgroundColor: COLORS.secondaryLightColor,
    borderRadius: 5,
    padding: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  lastCommunicationLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  LastCommunicationIcon: {
    marginRight: 5,
  },
  lastCommunicationText: {
    color: COLORS.secondaryFontColor,
    fontSize: 10,
    fontFamily: "Manrope-Regular",
    textAlign: "right",
  },
  lastCommunicationTimeText: {
    color: COLORS.secondaryFontColor,
    fontSize: 10,
    fontFamily: "Manrope-Regular",
    textAlign: "right",
  },
  datePickerSection: {
    marginBottom: 20,
    gap: 10,
  },
  datePickerLabel: {
    fontSize: 16,
    fontFamily: "Manrope-SemiBold",
    color: COLORS.primaryFontColor,
    marginBottom: 10,
  },
  tableContainer: {
    paddingHorizontal: 16,
  },
  tableTitle: {
    fontSize: 16,
    fontFamily: "Manrope-SemiBold",
    color: COLORS.primaryFontColor,
  },
  tableScrollWrapper: {
    paddingHorizontal: 16,
    marginTop: 10,
  },
  tableScrollContent: {
    paddingBottom: 10,
  },
  tableContent: {
    minWidth: 800,
  },
  alertsTable: {
    paddingHorizontal: 0,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "flex-start",
  },
  statusBadgeText: {
    fontFamily: "Manrope-SemiBold",
    fontSize: 12,
  },
  statusBlinkDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  meterSiCell: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  meterSiText: {
    color: COLORS.primaryFontColor,
    fontFamily: "Manrope-Medium",
    fontSize: 12,
  },
  statusResolved: {
    backgroundColor: "#DEF5E5",
  },
  statusResolvedText: {
    color: "#1E7A3F",
  },
  statusActive: {
    backgroundColor: "#FFF4E5",
  },
  statusActiveText: {
    color: "#C17B00",
  },
  actionButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E2E6F0",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.secondaryFontColor,
  },
  viewTableButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.secondaryFontColor,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginTop: 15,
    borderWidth: 1,
    borderColor: COLORS.secondaryColor,
  },
  viewTableButtonText: {
    fontSize: 14,
    fontFamily: "Manrope-SemiBold",
    color: COLORS.secondaryColor,
    marginRight: 8,
  },
  chartInstructionText: {
    fontSize: 11,
    fontFamily: "Manrope-Regular",
    color: COLORS.primaryFontColor,
    opacity: 0.7,
    textAlign: "center",
    marginTop: 8,
    marginBottom: 5,
  },
  negativeTrendContainer: {
    backgroundColor: "#FF6B6B",
  },
  toggleContainer: {
    flexDirection: "row",
    backgroundColor: COLORS.secondaryFontColor,
    borderRadius: 6,
    padding: 2,
    borderWidth: 1,
    borderColor: "#E2E6F0",
    height: 32,
  },
  toggleButton: {
    paddingHorizontal: 14,
    paddingVertical: 4,
    borderRadius: 4,
    minWidth: 65,
    alignItems: "center",
    justifyContent: "center",
    height: 28,
  },
  toggleButtonFullWidth: {
    flex: 1,
  },
  toggleButtonActive: {
    backgroundColor: COLORS.secondaryColor,
  },
  toggleTextActive: {
    color: COLORS.secondaryFontColor,
    fontSize: 12,
    fontFamily: "Manrope-SemiBold",
  },
  toggleTextInactive: {
    color: COLORS.primaryFontColor,
    fontSize: 12,
    fontFamily: "Manrope-Medium",
  },
  consumptionTable: {
    paddingHorizontal: 0,
    paddingVertical: 8,
  },
  consumptionValue: {
    color: COLORS.secondaryColor,
    fontFamily: "Manrope-SemiBold",
    fontSize: 12,
  },
  cumulativeValue: {
    color: COLORS.primaryFontColor,
    fontFamily: "Manrope-Medium",
  },
  usageStatsContainer: {
    paddingHorizontal: 16,
    paddingVertical: 5,
    gap: 10,
  },
  usageStatsTopRow: {
    flexDirection: "row",
    gap: 11,
  },
  usageStatsCard: {
    flex: 1,
    backgroundColor: "#eef8f0",
    borderRadius: 5,
    padding: 16,
  },
  usageStatsCardTitle: {
    fontSize: 12,
    fontFamily: "Manrope-Medium",
    color: COLORS.primaryFontColor,
    marginBottom: 8,
  },
  usageStatsCardValueBlue: {
    fontSize: 18,
    fontFamily: "Manrope-Bold",
    color: colors.color_brand_blue,
    lineHeight: 28,
  },
  usageStatsCardValueRed: {
    fontSize: 18,
    fontFamily: "Manrope-Bold",
    color: "#E53935",
    lineHeight: 28,
  },
  comparisonCard: {
    backgroundColor: "#eef8f0",
    borderRadius: 5,
    padding: 16,
  },
  comparisonHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    gap: 8,
  },
  doubleArrowIcon: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  doubleArrowText: {
    fontSize: 16,
    color: COLORS.primaryFontColor,
  },
  comparisonTitle: {
    fontSize: 12,
    fontFamily: "Manrope-Medium",
    color: COLORS.primaryFontColor,
  },
  monthlyValuesContainer: {
    flexDirection: "row",
    marginBottom: 12,
  },
  monthlyValueItem: {
    alignItems: "flex-start",
    flex: 1,
  },
  monthlyValueItem2: {
    alignItems: "flex-end",
  },
  monthlyValueLabel: {
    fontSize: 12,
    fontFamily: "Manrope-Regular",
    color: COLORS.primaryFontColor,
    marginBottom: 4,
  },
  monthlyValueBlue: {
    fontSize: 20,
    fontFamily: "Manrope-Bold",
    color: colors.color_brand_blue,
    lineHeight: 28,
  },
  monthlyValueGrey: {
    fontSize: 20,
    fontFamily: "Manrope-Bold",
    color: colors.color_text_secondary,
    lineHeight: 28,
  },
  monthlyValueRed: {
    fontSize: 20,
    fontFamily: "Manrope-Bold",
    color: "#E53935",
    lineHeight: 28,
  },
  excessUsageMessage: {
    color: "#E53935",
  },
  progressBarContainer: {
    marginBottom: 8,
  },
  progressBar: {
    flexDirection: "row",
    height: 8,
    borderRadius: 4,
    overflow: "hidden",
    backgroundColor: "#E5E7EB",
  },
  progressBarFill: {
    backgroundColor: colors.color_secondary,
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
  },
  progressBarRemainder: {
    backgroundColor: "transparent",
  },
  progressBarRemainderGray: {
    backgroundColor: "#D1D5DB",
  },
  savingsMessageRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  savingsMessageIcon: {
    marginRight: 8,
  },
  savingsMessage: {
    fontSize: 11,
    fontFamily: "Manrope-Medium",
    color: colors.color_secondary,
    textAlign: "center",
  },
  moreUsageMessage: {
    color: colors.color_secondary,
  },
});

export function useDarkOverlay(isDark, themeColors) {
  return useMemo(() => isDark ? {
    container: { backgroundColor: themeColors.screen },
    contentOnTop: { backgroundColor: themeColors.screen },
    amountSection: { backgroundColor: themeColors.screen },
    amountContainer: { backgroundColor: "#163B7C" },
    dueText: { color: themeColors.textPrimary },
    dateText: { color: themeColors.textSecondary },
    greenBox: { backgroundColor: COLORS.secondaryColor },
    paynowbox: { backgroundColor: COLORS.secondaryFontColor },
    paynowText: { color: COLORS.primaryFontColor },
    dueDaysText: { color: themeColors.textSecondary },
    meterContainer: { backgroundColor: themeColors.screen },
    meterInfoContainer: { backgroundColor: "#163B7C" },
    meterConsumerText: { color: themeColors.textPrimary },
    LastCommunicationText: { color: themeColors.textSecondary },
    tapIndicator: { backgroundColor: themeColors.accent },
    tapIndicatorText: { color: themeColors.textOnPrimary },
    meterNumberText: { color: themeColors.textPrimary },
    lastCommunicationTimeText: { color: themeColors.textSecondary },
    graphSection: {},
    energyText: { color: themeColors.textPrimary },
    pickDateRow: { backgroundColor: "#1A1F2E" },
    pickDateText: { color: themeColors.textPrimary },
    graphsContainer: { backgroundColor: "#1A1F2E" },
    thismonthText: { color: themeColors.textPrimary },
    kwhText: { color: themeColors.accent },
    lastText: { color: themeColors.textSecondary },
    viewDropdownButton: { backgroundColor: themeColors.accent },
    viewDropdownButtonText: { color: themeColors.textOnPrimary },
    viewDropdownContent: { backgroundColor: themeColors.card, borderColor: themeColors.cardBorder },
    viewDropdownItem: { borderBottomColor: themeColors.cardBorder },
    viewDropdownItemText: { color: themeColors.textPrimary },
    viewDropdownItemSelected: { backgroundColor: themeColors.accent + "20" },
    viewDropdownItemTextSelected: { color: themeColors.accent },
    timePeriodButton: {},
    timePeriodButtonActive: { backgroundColor: themeColors.brandBlue },
    timePeriodButtonText: { color: themeColors.textPrimary },
    timePeriodButtonTextActive: { color: themeColors.textOnPrimary },
    usageStatsCard: { backgroundColor: "#1A1F2E", borderColor: themeColors.cardBorder },
    usageStatsCardTitle: { color: themeColors.textSecondary },
    usageStatsCardValueBlue: { color: themeColors.brandBlue },
    usageStatsCardValueRed: { color: themeColors.danger },
    comparisonCard: { backgroundColor: "#1A1F2E", borderColor: themeColors.cardBorder },
    comparisonTitle: { color: themeColors.textPrimary },
    monthlyValueLabel: { color: themeColors.textSecondary },
    monthlyValueBlue: { color: themeColors.brandBlue },
    monthlyValueGrey: { color: themeColors.textSecondary },
    progressBar: { backgroundColor: themeColors.progressBarTrack },
    progressBarFill: { backgroundColor: themeColors.accent },
    savingsMessage: { color: themeColors.savingsText },
    moreUsageMessage: { color: themeColors.savingsText },
    tableTitle: { color: themeColors.textPrimary },
    tableContainer: {},
    meterSiText: { color: themeColors.textPrimary },
    consumptionValue: { color: themeColors.accent },
    cumulativeValue: { color: themeColors.textPrimary },
  } : {}, [isDark, themeColors]);
}
